spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookapp?serverTimezone=Asia/Seoul
    username: bookapp
    password: bookapp123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

aladin:
  base-url: https://www.aladin.co.kr/ttb/api/
  ttb-key: "ttbmr87741133001"
