spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookapp?serverTimezone=Asia/Seoul&characterEncoding=utf8mb4
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

aladin:
  base-url: https://www.aladin.co.kr/ttb/api/
  ttb-key: "ttbmr87741133001"
